const gridData = [
  {
    id: 549731,
    artist: "Birdy",
    release: "2016.03.26",
    type: "CASE A",
    typeCode: "1",
    genre: "Pop",
    genreCode: "1",
    grade: "2",
    reportBtn: "<button class='reportBtn'>신고하기</button>",
  },
  {
    id: 436461,
    artist: "Ed Sheeran",
    release: "2014.06.24",
    type: "CASE A",
    typeCode: "1",
    genre: "Pop",
    genreCode: "1",
    grade: "3",
    reportBtn: "<button class='reportBtn'>신고하기</button>",
  },
  {
    id: 295651,
    release: "2011.08.08",
    artist: "Maroon5",
    type: "CASE A",
    typeCode: "3",
    genre: "Pop,Rock",
    genreCode: "1,2",
    grade: "2",
    reportBtn: "<button class='reportBtn'>신고하기</button>",
  },
  {
    id: 541713,
    name: "A Head Full Of Dreams",
    artist: "Coldplay",
    release: "2015.12.04",
    type: "CASE A",
    typeCode: "1",
    genre: "Rock",
    genreCode: "2",
    grade: "3",
    reportBtn: "<button class='reportBtn'>신고하기</button>",
  },
  {
    id: 265289,
    name: "21",
    artist: "Adele",
    release: "2011.01.21",
    type: "CASE A",
    typeCode: "1",
    genre: "Pop,R&B",
    genreCode: "1,3",
    grade: "3",
    reportBtn: "<button class='reportBtn'>신고하기</button>",
  },
  {
    id: 555871,
    name: "Warm On A Cold Night",
    artist: "HONNE",
    release: "2016.07.22",
    type: "CASE A",
    typeCode: "1",
    genre: "R&B,Electronic",
    genreCode: "3,4",
    grade: "2",
    reportBtn: "<button class='reportBtn'>신고하기</button>",
  },
  {
    id: 550571,
    name: "Take Me To The Alley",
    artist: "Gregory Porter",
    release: "2016.09.02",
    type: "CASE A",
    typeCode: "1",
    genre: "Jazz",
    genreCode: "5",
    grade: "3",
    reportBtn: "<button class='reportBtn'>신고하기</button>",
  },
  {
    id: 544128,
    artist: "LANY",
    release: "2015.12.11",
    type: "CASE A",
    typeCode: "2",
    genre: "Electronic",
    genreCode: "4",
    grade: "2",
    reportBtn: "<button class='reportBtn'>신고하기</button>",
  },
  {
    id: 366374,
    artist: "Daft Punk",
    release: "2013.04.23",
    type: "CASE A",
    typeCode: "3",
    genre: "Pop,Funk",
    genreCode: "1,5",
    grade: "3",
    reportBtn: "<button class='reportBtn'>신고하기</button>",
  },
  {
    id: 8012747,
    artist: "Sigur Rós",
    release: "2012.05.31",
    type: "CASE A",
    typeCode: "3",
    genre: "Rock",
    genreCode: "2",
    grade: "3",
    reportBtn: "<button class='reportBtn'>신고하기</button>",
  },
  {
    id: 502792,
    artist: "Snoop Dogg",
    release: "2015.05.12",
    type: "CASE A",
    typeCode: "2",
    genre: "Hiphop",
    genreCode: "5",
    grade: "3",
    reportBtn: "<button class='reportBtn'>신고하기</button>",
  },
  {
    id: 294574,
    artist: "Beyoncé",
    release: "2011.07.26",
    type: "CASE A",
    typeCode: "1",
    genre: "Pop",
    genreCode: "1",
    grade: "3",
    reportBtn: "<button class='reportBtn'>신고하기</button>",
  },
  {
    id: 317659,
    artist: "Jason Mraz",
    release: "2012.01.03",
    type: "CASE A",
    typeCode: "3",
    genre: "Pop",
    genreCode: "1",
    reportBtn: "<button class='reportBtn'>신고하기</button>",
    grade: "2",
  },
  {
    id: 583551,
    artist: "Craig David",
    release: "2016.10.01",
    type: "CASE A",
    typeCode: "1",
    genre: "R&B,Electronic",
    genreCode: "3,4",
    grade: "3",
    reportBtn: "<button class='reportBtn'>신고하기</button>",
  },
];

const grid = new tui.Grid({
  el: document.getElementById("grid1"),
  data: gridData,
  scrollX: false,
  scrollY: false,
  minBodyHeight: 30,
  rowHeaders: ["rowNum"],
  pageOptions: {
    useClient: true,
    perPage: 5,
  },
  header: {
    height: 120,
    complexColumns: [
      {
        header: "상황 A 그리드",
        name: "mergeColumn3",
        childNames: ["id", "artist", "type", "release", "genreCode"],
      },
    ],
  },
  columns: [
    {
      header: "유저 ID",
      name: "id",
      align: "center",
      sortable: true,
    },

    {
      header: "이름",
      name: "artist",
      align: "center",
      filter: {
        type: 'text',
        showApplyBtn: true,
        showClearBtn: true
      }
    },
    {
      header: "로그 타입",
      name: "type",
      align: "center",
    },
    {
      header: "생성 날짜",
      name: "release",
      align: "center",
      sortable: true,
    },
    {
      header: "코드",
      name: "genreCode",
      align: "center",
      sortable: true,
    },
    {
      header: "신고 버튼",
      name: "reportBtn",
      align: "center",
    },
  ],
});
